---
- name: Lesson 1 Exercise 3A
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Print output of ansible_host to stdout
      debug:
        var: ansible_host

- name: Lesson 1 Exercise 3C
  hosts: cisco
  gather_facts: False
  tasks:
    - name: Print ansible_connection variable
      debug:
        var: ansible_connection

    - name: Print ansible_host variable
      debug:
        var: ansible_host