---
- name: Lesson 2 Exercise 4A
  hosts: cisco6
  gather_facts: False
  tasks:
    - name: Clear the logging buffer
      ios_command:
        commands: 
          - command: clear logging
            prompt: confirm
            answer: "\r"
      register: clear_log_output

    - name: Print clear log output 
      debug:
        var: clear_log_output
            