---
- name: Lesson 4 Exercise 3
  hosts: nxos
  gather_facts: False
  tasks:
    - name: Configure IP On NX-OS Switches
      nxos_interfaces:
        config:
          - name: "{{ intf_name }}"
            enabled: True
            mode: layer3
        state: merged

    - name: Configure IPv4 Address
      nxos_l3_interfaces:
        config:
          - name: "{{ intf_name }}"
            ipv4:
              - address: "{{ intf_address }}/{{ intf_netmask }}"
        state: merged

    - name: Ping across interfaces
      net_ping:
        dest: "{{ peer_ip }}"
      register: output

    - name: Verify at least four ping responses received
      assert:
        that:
          - output.packets_rx >= 4
