---
- name: Lesson 4 Exercise 2
  hosts: cisco1
  gather_facts: False
  tasks:
    - name: Configure the cisco1 switch
      ios_system:
        hostname: "{{ hostname }}"
        domain_name: "{{ domain_name }}"
        name_servers:
          - "{{ dns_server1 }}"
          - "{{ dns_server2 }}"