---
- name: Lesson 2 Exercise 6A/B
  hosts: arista
  gather_facts: False
  tasks:
    - name: Arista Show IP ARP
      eos_command:
        commands: show ip arp | json
      register: arista_show_ip_arp

    - name: Print arista_show_ip_arp
      debug:
        var: arista_show_ip_arp
