---
- name: Lesson 3 Exercise 3
  hosts: cisco1:cisco2
  gather_facts: False
  tasks:
    - name: Retrieve Show LLDP Neighbors IOS
      ios_command:
        commands: show lldp neighbors
      register: lldp_output

    - name: Set LLDP Nei IOS Variable
      set_fact:
        lldp: "{{ lldp_output ['stdout_lines'][0] }}"

    - name: Extract LLDP entry from list of lines
      set_fact:
        lldp_entry: "{{ item }}"
      loop: "{{ lldp }}"
      when: "'twb-sf-hpsw1' in item"

    - name: Set LLDP variables from the .split() output
      set_fact:
        remote_device: "{{ lldp_entry.split()[0] }}"
        local_intf: "{{ lldp_entry.split()[1] }}"
        remote_intf: "{{ lldp_entry.split()[-1] }}"

    - name: Display results
      debug:
        msg:
          - "Remote Device: {{ remote_device }}"
          - "Local Intf: {{ local_intf }}"
          - "Remote Intf: {{ remote_intf }}"